In [ ]:
# 1. Import libraries and data frame.
# 2. Ran statistical checks to see what makes sense to report on.

In [2]:
# Import libraries, the last three for data visualizations
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [3]:
# define path
path = r'C:\Users\Administrator\Documents\data analytics\Instacart Basket Analysis\02 Data\Prepared data'

In [4]:
# import ords_prods_custs. I call it opc to have a short name.
opc_filt = pd.read_pickle(os.path.join(path, 'ord-prod-cust_filtered.pkl'))

In [5]:
opc_filt.head(2) # Quick check of files

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2539329        1             1                   2                  8   

   days_since_prior_order validation  product_id  add_to_cart_order  \
0                     NaN      prior       196.0                1.0   
1                     NaN      prior     14084.0                2.0   

   reordered  ... frequency_flag  gender    state  age  date_joined  \
0        0.0  ...            NaN  Female  Alabama   31    2/17/2019   
1        0.0  ...            NaN  Female  Alabama   31    2/17/2019   

  n_dependants fam_status income  region  Exclude  
0            3    married  40423   South    False  
1            3    married  40423   South    False  

[2 rows x 33 columns]

In [6]:
# Check distribution of age to understand how to profile customers
opc_filt['age'].unique()

array([31, 68, 33, 75, 39, 34, 73, 46, 51, 66, 69, 36, 58, 62, 47, 71, 78,
       37, 59, 81, 54, 28, 38, 80, 43, 76, 57, 27, 48, 70, 41, 53, 25, 22,
       67, 64, 19, 29, 65, 49, 45, 74, 50, 32, 26, 79, 30, 72, 18, 60, 77,
       52, 55, 24, 44, 42, 61, 63, 40, 21, 20, 56, 35, 23], dtype=int64)

In [7]:
print(opc_filt.columns)

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'validation',
       'product_id', 'add_to_cart_order', 'reordered', '_merge',
       'product_name', 'aisle_id', 'department_id', 'prices',
       'price_range_loc', 'busiest day', 'busiest_hour', 'max_order',
       'average_price', 'spending_flag', 'loyalty_flag', 'avg_price',
       'frequency_flag', 'gender', 'state', 'age', 'date_joined',
       'n_dependants', 'fam_status', 'income', 'region', 'Exclude'],
      dtype='object')


In [8]:
opc_filt['department_id'].unique()

array([ 7., 16., 19., 17.,  4., 14., 13., nan, 20.,  1., 11., 12.,  6.,
        3., 15.,  9.,  5.,  8.,  2., 21., 18., 10.])

In [9]:
opc_filt['product_name'].unique()

array(['Soda', 'Organic Unsweetened Vanilla Almond Milk',
       'Original Beef Jerky', ..., 'Orange Energy Shots',
       'Ultragrain Tortillas 8 Taco Size',
       'Hot Oatmeal Multigrain Raisin'], dtype=object)

In [10]:
opc_filt['product_id'].unique()

array([  196., 14084., 12427., ..., 43553., 42050., 28818.])

In [82]:
# New column for income group defining low, medium or high income level

opc_filt.loc[opc_filt['income'] <= 30000, 'income group'] = 'Low'
opc_filt.loc[(opc_filt['income'] > 30000) & (opc_filt['income'] <= 70000), 'income group'] = 'Medium'
opc_filt.loc[opc_filt['income'] > 70000, 'income group'] = 'High'

In [83]:
opc_filt['income group'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [81]:
# New column for age group defining Young, Adult or Senior age group

opc_filt.loc[opc_filt['age'] <= 20, 'Age Group'] = 'Young'
opc_filt.loc[(opc_filt['age'] > 21) & (opc_filt['age'] <= 55), 'Age Group'] = 'Adult'
opc_filt.loc[opc_filt['age'] > 60, 'Age Group'] = 'Senior'

In [77]:
opc_filt['Age Group'].unique()

array(['Adult', 'Senior', nan, 'Young'], dtype=object)

In [84]:
opc_filt.loc[opc_filt['n_dependants'] > 0, 'dependants flag'] = 'Yes'
opc_filt.loc[opc_filt['n_dependants'] <= 0, 'dependants flag'] = 'No'



In [85]:
opc_filt['dependants flag'].unique()

array(['Yes', 'No'], dtype=object)

In [88]:
# Start with a default profile
opc_filt['shopper_profile'] = 'Other'

# Convenience shopper: soda, beef, chips, frozen etc.
opc_filt.loc[
    opc_filt['product_name'].str.contains('soda|beef|chips|frozen|pizza', case=False, na=False),
    'shopper_profile'
] = 'Convenience Shopper'

# Healthy eater: energy bars, organic, vitamins, kale, smoothie
opc_filt.loc[
    opc_filt['product_name'].str.contains('organic|energy|vitamin|kale|smoothie', case=False, na=False),
    'shopper_profile'
] = 'Healthy Eater'

# Sweet tooth: candy, chocolate, ice cream
opc_filt.loc[
    opc_filt['product_name'].str.contains('candy|chocolate|ice cream|cookie', case=False, na=False),
    'shopper_profile'
] = 'Sweet Tooth'



In [90]:
opc_filt['product_name'].unique()

array(['Soda', 'Organic Unsweetened Vanilla Almond Milk',
       'Original Beef Jerky', ..., 'Orange Energy Shots',
       'Ultragrain Tortillas 8 Taco Size',
       'Hot Oatmeal Multigrain Raisin'], dtype=object)

In [91]:
opc_filt['shopper_profile'].value_counts().loc['Sweet Tooth']

1202099